### ISSUE TITLE
Can't change default user password or add users

### ISSUE THREAD

**Issue by ichiemo** [bunkeriot/BunkerM#28]
**Describe the bug**
I can't edit the default user and I cannot add any new users in the webui after deploying the docker container on a docker host. I have tried both latest and v1.2.0 of the container image. 

**To Reproduce**
1. Spin up the docker container via docker compose (Below will be the docker-compose I made out of the docker run command from the docs)
2. Login with default credentials
3. Click on upper right 3 dot menu > Account Settings
4. Only option available is delete(trash can icon) which is greyed out for the admin user
5. Click Add User
6. Fill out new user fields and click green 'Create User' button
7. Red banner at the bottom pops up saying 'Error creating user'

**Expected behavior**
I expect to be able to change the admin password and add users.

**Screenshots**

<img width="1507" alt="Image" src="https://github.com/user-attachments/assets/3bef7b76-3e6e-4901-a6e2-fbb3e1d89af3" />

![Image](https://github.com/user-attachments/assets/163c2935-fd0c-4616-88ba-3d232929123e)

**Desktop (please complete the following information):**
 - OS: MacOS/Windows
 - Browser: Safari/Edge/Chrome
 - Version: Latest versions of OS and Browsers

**Additional Information**

docker-compose.yml edited to make the paths easier to read in the volumes and removed the ip.

```
services:
  MQTT:
    image: bunkeriot/bunkerm:latest
    container_name: bunkermqtt
    restart: unless-stopped
    environment:
      - HOST_ADDRESS=host-ip-address  # Change this for remote access Host IP or Domain
    ports:
      - "1900:1900"
      - "2000:2000"
    volumes:
      - .../docker/appdata/mosquitto_data:/var/lib/mosquitto
      - .../docker/appdata/auth_data:/data
```

**Comment by Dinth** [comment]
same issue here, just created a brand new instance to test how does it look like. Also using HOST_ADDRESS.

**Comment by JSylvia007** [comment]
Figured I'd jump in here too and say that I'm having this same issue...  I would like to run this behind my nginx proxy manager, but no matter what variables I set, I can't make it work...  It always still tries to reach out to localhost...

**Comment by icoco** [comment]
```
AccountManager.vue:214 Error creating user TypeError: crypto.randomUUID is not a function
    at D (AccountManager.vue:177:18)
```

how to fix this issue ?

**Comment by icoco** [comment]
this code still need more prefect and stable,  I have choice another [TBMQ](https://github.com/thingsboard/tbmq), it is more easy to deploy .

**Comment by MKoroschetz** [comment]
same here, unable to create users and clients. admin password reset ends with error following the instructions
It looks promising, but without being able to manage users it not worth trying to make it work. The documentation is quite extensive but not helpful for actually solving problems.

**Comment by IIIdefconIII** [comment]
hi dev, is this still active im new im having the same trouble

I also did cmod 0700 on the mosquitto_passwd because i tought that extra 0 in front was a typo on first log info i got out of portainer and dozzle:

I also tried cmod 700 the mosquitto_passwd file and restarten, im not sure what im doing rong,

The container log doesnt give me back that there is something wrong.

Could you suggest me what to check next?

EDIT: ie even tried incognito mode on firefox
EDIT2: Creating a new user also get a fail status:
Error creating user so i guess its something with the db file, im going ot check that chmod 700 on the db file aswell, ill report back
EDIT3: i even chmod all files to 777 but im still getting this error:

<img width="580" height="760" alt="Image" src="https://github.com/user-attachments/assets/9bf23450-4104-4e18-90f0-90d38fb11bcb" />

Running on  synology sys with 40 perfect configured containers:
```

  bunkerm:
    container_name: bunkerm
    image: bunkeriot/bunkerm

    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 1900:1900
      - 2000:2000
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK
      TZ: $TZ
      HOST_ADRESS: 10.3.10.10
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - $DOCKERDIR/bunkerm:/var/lib/mosquitto
      - $DOCKERDIR/bunkerm/mosquitto_conf:/etc/mosquitto
      - $DOCKERDIR/bunkerm/auth_data:/data
```

could it has to run on other PUID and GUID then a synology admin account?

**Comment by IIIdefconIII** [comment]
> 
> services:
>   MQTT:
>     image: bunkeriot/bunkerm:latest
>     container_name: bunkermqtt
>     restart: unless-stopped
>     environment:
>       - HOST_ADDRESS=host-ip-address  # Change this for remote access Host IP or Domain
>     ports:
>       - "1900:1900"
>       - "2000:2000"
>     volumes:
>       - .../docker/appdata/mosquitto_data:/var/lib/mosquitto
>       - .../docker/appdata/auth_data:/data
> ```

did you tried several PUID and GUID for the container?

**Comment by icoco** [comment]
this obviously just a demo app ， many uncompleted feature yet,  unless have time to fix or else choice other mqtt broker is best :-)

**Comment by IIIdefconIII** [comment]
> this obviously just a demo app ， many uncompleted feature yet, unless have time to fix or else choice other mqtt broker is best :-)

ah the screenshot looked nice and i was like either this app or try bevywise

**Comment by mstewart14** [comment]
Thought I'd try again and had a different bad experience.  Very similar to the above (still can't successfully create a user and  log in).  
Used the new documentation to setup a new docker compose file 
```
services:
  bunkerm:
    image: bunkeriot/bunkerm:latest
    container_name: bunkermqtt
    restart: unless-stopped
    environment: 
      HOST_ADDRESS: "<internal docker host IP>"
    ports:
      - "1900:1900"
      - "2000:2000"
    volumes:
      - "./bunkerm_data:/nextjs/data"
      - "./mosq_data:/var/lib/mosquitto"
      - "./mosq_conf:/etc/mosquitto"
```
Followed the prompts for a first setup and created a user and password (or so I thought).
Got to the initial login prompt, used the credentials AND... the screen didn't change.  Stayed on the login screen, no error visible) no nothing.
Tried to register another user, on registration the system threw the following error in the console.

> NotFoundError: Node.insertBefore: Child to insert before is not a child of this node [bootstrap-autofill-overlay.js:5512:30](moz-extension://63238c32-c8b1-4629-8a11-780dd70edb94/content/bootstrap-autofill-overlay.js)
> Cookie “bunkerm_token” has been rejected because a non-HTTPS cookie can’t be set as “secure”. [register](http://<internal docker host ip>:2000/api/auth/register)
> NotFoundError: Node.insertBefore: Child to insert before is not a child of this node

why is it requiring https?  Documentation doesn't mention it.

On startup the following errors were logged
WARN exited: mosquitto (exit status 3; not expected)
INFO spawned: 'mosquitto' with pid 93
WARN exited: mosquitto (exit status 3; not expected)
INFO spawned: 'mosquitto' with pid 94
WARN exited: mosquitto (exit status 3; not expected)
INFO gave up: mosquitto entered FATAL state, too many start retries too quickly

So it looks like it can't successfully launch Mosquitto (which might explain the lack of success logging in??)

Subsequent attempts to log in as any of the users created results in the following in the console:

> XHRGET http://<internal docker host IP>:2000/api/auth/me [HTTP/1.1 401 Unauthorized 45ms]
> XHRPOST http://<internal docker host IP>:2000/api/auth/login [HTTP/1.1 401 Unauthorized 85ms]

AND an "invalid credentials" error on screen.  

Trying to reset the password onscreen (since it's not connected to anything to send with) allowed me to change the password (apparently) but resulted in the same behaviour (can't login).  

Looking through the created files from the setup looks like users.json is getting the correct data for the users and is setting hashed passwords in there.  The mostquitto directories were empty (since... go figure Mosquitto isn't running).
