### ISSUE TITLE
WARN exited: mosquitto (exit status 3; not expected)

### ISSUE THREAD

**Issue by Dinth** [bunkeriot/BunkerM#29]
**Describe the bug**
I have set up a new instance of BunkerM, using the following docker compose:
```
services:
  bunkerm:
    image: bunkeriot/bunkerm
    container_name: bunkerm
    restart: unless-stopped
    ipc: private
    environment: 
      HOST_ADDRESS: "10.10.1.13"
    ports:
      - "1900:1900"
      - "2000:2000"
    volumes:
      - "/opt/docker/bunkerm/bunkerm_data:/var/lib/mosquitto"
      - "/opt/docker/bunkerm/bunkerm_config:/etc/mosquitto"
      - "/opt/docker/bunkerm/bunkerm_auth:/data"
    networks:
      - bunkerm
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
networks:
  bunkerm:
    name: bunkerm
    driver: bridge

```
but it looks like Mosquitto process is constantly crashing:
```
bunkerm  | 2025-06-11T20:22:02.187675323Z Runtime configuration set to use host: 10.10.1.13
bunkerm  | 2025-06-11T20:22:02.187727811Z Firebase Auth will use proxy at http://10.10.1.13:2000/auth/
bunkerm  | 2025-06-11T20:22:02.576197741Z 2025-06-11 20:22:02,575 INFO Set uid to user 0 succeeded
bunkerm  | 2025-06-11T20:22:02.586606523Z 2025-06-11 20:22:02,586 INFO supervisord started with pid 1
bunkerm  | 2025-06-11T20:22:03.590365204Z 2025-06-11 20:22:03,589 INFO spawned: 'mosquitto' with pid 34
bunkerm  | 2025-06-11T20:22:03.591957499Z 2025-06-11 20:22:03,591 INFO spawned: 'auth-api' with pid 35
bunkerm  | 2025-06-11T20:22:03.593728756Z 2025-06-11 20:22:03,593 INFO spawned: 'aws-bridge-api' with pid 36
bunkerm  | 2025-06-11T20:22:03.595655174Z 2025-06-11 20:22:03,595 INFO spawned: 'azure-bridge-api' with pid 37
bunkerm  | 2025-06-11T20:22:03.597598482Z 2025-06-11 20:22:03,597 INFO spawned: 'clientlogs' with pid 38
bunkerm  | 2025-06-11T20:22:03.599956881Z 2025-06-11 20:22:03,599 INFO spawned: 'config-api' with pid 39
bunkerm  | 2025-06-11T20:22:03.603133859Z 2025-06-11 20:22:03,602 INFO spawned: 'dynsec-api' with pid 40
bunkerm  | 2025-06-11T20:22:03.606134444Z 2025-06-11 20:22:03,605 INFO spawned: 'monitor-api' with pid 41
bunkerm  | 2025-06-11T20:22:03.608278476Z 2025-06-11 20:22:03,607 INFO spawned: 'nginx' with pid 42
bunkerm  | 2025-06-11T20:22:03.609255914Z 2025-06-11 20:22:03,609 WARN exited: mosquitto (exit status 3; not expected)
bunkerm  | 2025-06-11T20:22:04.754076152Z 2025-06-11 20:22:04,753 INFO spawned: 'mosquitto' with pid 79
bunkerm  | 2025-06-11T20:22:04.754423589Z 2025-06-11 20:22:04,754 INFO success: auth-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.754543224Z 2025-06-11 20:22:04,754 INFO success: aws-bridge-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.754841222Z 2025-06-11 20:22:04,754 INFO success: azure-bridge-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.754908828Z 2025-06-11 20:22:04,754 INFO success: clientlogs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.755105090Z 2025-06-11 20:22:04,754 INFO success: config-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.755448807Z 2025-06-11 20:22:04,755 INFO success: dynsec-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.755742924Z 2025-06-11 20:22:04,755 INFO success: monitor-api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.756077868Z 2025-06-11 20:22:04,755 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bunkerm  | 2025-06-11T20:22:04.764729956Z 2025-06-11 20:22:04,764 WARN exited: mosquitto (exit status 3; not expected)
bunkerm  | 2025-06-11T20:22:07.120150257Z 2025-06-11 20:22:07,119 INFO spawned: 'mosquitto' with pid 106
bunkerm  | 2025-06-11T20:22:07.126937661Z 2025-06-11 20:22:07,126 WARN exited: mosquitto (exit status 3; not expected)
bunkerm  | 2025-06-11T20:22:10.133019590Z 2025-06-11 20:22:10,132 INFO spawned: 'mosquitto' with pid 107
bunkerm  | 2025-06-11T20:22:10.142296572Z 2025-06-11 20:22:10,142 WARN exited: mosquitto (exit status 3; not expected)
bunkerm  | 2025-06-11T20:22:11.143730098Z 2025-06-11 20:22:11,143 INFO gave up: mosquitto entered FATAL state, too many start retries too quickly
```
**To Reproduce**
1. Just deploy a new stack using the docker-compose above

**Expected behavior**
Mosquito process should crash.

**Additional context**
The mosquitto logs at /var/log/mosquito/ are empty

**Comment by akosfonod** [comment]
Hi @Dinth,
I have stumbled upon the same issue, or I hope this might help you to go further.
I also mapped the as a local volume the`./mosquitto-provision/:/etc/mosquitto/` folder **as suggested in the readme** and apparently that is causing the issue. (Tough I do not know how to fix it yet.)
To be able to see all the logs I have also mapped the `/var/log/supervisor/` folder and there I was able to see mosquitto's error output:
```
1750107948: Error: Unable to open config file /etc/mosquitto/mosquitto.conf.
1750107949: Error: Unable to open config file /etc/mosquitto/mosquitto.conf.
1750107951: Error: Unable to open config file /etc/mosquitto/mosquitto.conf.
1750107954: Error: Unable to open config file /etc/mosquitto/mosquitto.conf.
```
Compose file used:
(note the commented-out /etc/mosquitto folder)
```yaml
x-logging: &limit_logging
  logging:
    driver: "json-file"
    options:
      max-size: "50m"

services:
  mosquitto:
    image: bunkeriot/bunkerm:v1.2.0
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "2000:2000" # BunkerM WEB UI
      - "8883:8883"
    volumes:
      # - ./mosquitto-provision/:/etc/mosquitto/
      - ./auth_data/:/data/
      - ./logs/:/var/log/supervisor/
    <<: *limit_logging
```
